### PR TITLE
[v6r22] SandboxStore: use host credentials to query the DB for async removal

### PR DESCRIPTION
**Pull request by chaen**
Fixes bug introduced in https://github.com/DIRACGrid/DIRAC/pull/4217
```
2019-08-22 08:09:50 UTC WorkloadManagement/SandboxStore ERROR: Exception while setting deletion request Traceback (most recent call last): 
File "/opt/dirac/pro/DIRAC/WorkloadManagementSystem/Service/SandboxStoreHandler.py", line 482, in __deleteSandboxFromExternalBackend credDict = self.getRemoteCredentials() 
File "/opt/dirac/pro/DIRAC/Core/DISET/RequestHandler.py", line 97, in getRemoteCredentials return self.__trPool.get(self.__trid).getConnectingCredentials()
AttributeError: 'NoneType' object has no attribute 'getConnectingCredentials' 

2019-08-22 08:09:50 UTC WorkloadManagement/SandboxStore ERROR: Cannot delete sandbox from backend Cannot set deletion request: 'NoneType' object has no attribute 'getConnectingCredentials'
```

Hot fixed in lhcb prod

BEGINRELEASENOTES

*WMS
FIX: use host credentials to query the SandboxMetadataDB for async removal

ENDRELEASENOTES

### CODE REVIEW

File: WorkloadManagementSystem/DB/SandboxMetadataDB.py [hunk 1]
```diff
@@ -348,10 +348,10 @@ def getSandboxId(self, SEName, SEPFN, requesterName, requesterGroup, field='SBId
       return S_ERROR("No sandbox matches the requirements")
     return S_OK(data[0][0])
 
-  def getSandboxOwner(self, SEName, SEPFN, requesterName, requesterGroup):
+  def getSandboxOwner(self, SEName, SEPFN, requesterDN, requesterGroup):
     """ get the sandbox owner, if such sandbox exists
```
Comment (fstagni) [inline WorkloadManagementSystem/DB/SandboxMetadataDB.py]: Since you are are it, can you add the parameters in the docstring? Also for `getSandboxId`.

Comment (chaen) [reply WorkloadManagementSystem/DB/SandboxMetadataDB.py]: OK

**Comment by chaen** [comment]
Added the docstring
